"""Make the project logo and favicon from the "GS" drawing in docs/logo/gs-drawing.json.

The SVGs look like the demo's drawing pad in its dark theme (web/demo/style.css): light
round-capped strokes on the grey pad, with rounded corners. ``logo.svg`` uses the pad's
pen width; ``favicon.svg`` uses a thicker line, because at 16–32 px the pad's width would
be under a pixel. The Android demo's launcher icons are vector drawables made the same way:
an adaptive icon (the drawing inside the 66 dp safe zone of its 108 dp canvas) and a plain
one for Android 7 (API 24–25).

Usage: ``uv run python -m glyphsketch.tools.logo``
"""

import json

import numpy as np

from glyphsketch.paths import REPO_ROOT
from glyphsketch.strokes import simplify_stroke

LOGO_DIR = REPO_ROOT / "docs" / "logo"
ANDROID_RES_DIR = REPO_ROOT / "android" / "demo" / "src" / "main" / "res"
DRAWING_FILE = LOGO_DIR / "gs-drawing.json"
INK = "#ececf0"  # --ink, dark theme
PAD = "#222228"  # --panel, dark theme
PAD_PEN_WIDTH = 6.0  # the demo draws 6 CSS px lines
PAD_CORNER = 8.0 / 340  # 8 px radius on the 340 px pad
MARGIN = 0.14  # of the square's side, around the drawing
SIMPLIFY_TOLERANCE = 0.4  # CSS px
ADAPTIVE_MARGIN = 0.27  # of 108 dp: the drawing stays inside the 66 dp safe zone
ICON_PEN_WIDTH = PAD_PEN_WIDTH * 2.5  # launcher icons are favicon-sized


def _fitted(
    strokes: list[np.ndarray], size: float, margin: float
) -> tuple[list[np.ndarray], float]:
    """The simplified strokes mapped into a size × size square, and the scale used."""
    points = np.concatenate(strokes)
    low, high = points.min(axis=0), points.max(axis=0)
    extent = float(max(high - low))
    side = extent / (1 - 2 * margin)
    origin = (low + high) / 2 - side / 2
    scale = size / side
    return [(simplify_stroke(s, SIMPLIFY_TOLERANCE) - origin) * scale for s in strokes], scale


def svg(strokes: list[np.ndarray], pen_width: float, size: int = 256) -> str:
    fitted, scale = _fitted(strokes, size, MARGIN)
    paths = []
    for stroke in fitted:
        coordinates = " ".join(f"{x:.1f},{y:.1f}" for x, y in stroke)
        paths.append(f'  <polyline points="{coordinates}"/>')
    corner = PAD_CORNER * size * 2
    return "\n".join(
        [
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {size} {size}" '
            f'width="{size}" height="{size}">',
            "  <title>glyphsketch</title>",
            f'  <rect width="{size}" height="{size}" rx="{corner:.1f}" fill="{PAD}"/>',
            f'  <g fill="none" stroke="{INK}" stroke-width="{pen_width * scale:.1f}" '
            'stroke-linecap="round" stroke-linejoin="round">',
            *["  " + path for path in paths],
            "  </g>",
            "</svg>",
            "",
        ]
    )


def android_vector(strokes: list[np.ndarray], margin: float, background: bool) -> str:
    """A VectorDrawable of the drawing on a 108 × 108 canvas."""
    size = 108
    fitted, scale = _fitted(strokes, size, margin)
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by glyphsketch.tools.logo from docs/logo/gs-drawing.json. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        f'    android:width="{size}dp" android:height="{size}dp"',
        f'    android:viewportWidth="{size}" android:viewportHeight="{size}">',
    ]
    if background:
        corner = PAD_CORNER * size * 2
        lines.append(
            f'    <path android:fillColor="{PAD}" android:pathData="M{corner:.1f},0 '
            f"H{size - corner:.1f} A{corner:.1f},{corner:.1f} 0 0 1 {size},{corner:.1f} "
            f"V{size - corner:.1f} A{corner:.1f},{corner:.1f} 0 0 1 {size - corner:.1f},{size} "
            f"H{corner:.1f} A{corner:.1f},{corner:.1f} 0 0 1 0,{size - corner:.1f} "
            f'V{corner:.1f} A{corner:.1f},{corner:.1f} 0 0 1 {corner:.1f},0 Z" />'
        )
    for stroke in fitted:
        data = "M" + " L".join(f"{x:.1f},{y:.1f}" for x, y in stroke)
        lines += [
            f'    <path android:pathData="{data}"',
            f'        android:strokeColor="{INK}" android:strokeWidth="{ICON_PEN_WIDTH * scale:.1f}"',
            '        android:strokeLineCap="round" android:strokeLineJoin="round" />',
        ]
    return "\n".join([*lines, "</vector>", ""])


ADAPTIVE_ICON = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by glyphsketch.tools.logo. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_foreground" />
</adaptive-icon>
"""

ICON_COLORS = f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by glyphsketch.tools.logo. -->
<resources>
    <color name="ic_launcher_background">{PAD}</color>
</resources>
"""


def main() -> None:
    raw = json.loads(DRAWING_FILE.read_text(encoding="utf-8"))
    strokes = [np.array(stroke, dtype=np.float64) for stroke in raw["strokes"]]
    outputs = {
        LOGO_DIR / "logo.svg": svg(strokes, PAD_PEN_WIDTH),
        LOGO_DIR / "favicon.svg": svg(strokes, PAD_PEN_WIDTH * 2.5),
        ANDROID_RES_DIR / "drawable" / "ic_launcher_foreground.xml": android_vector(
            strokes, ADAPTIVE_MARGIN, background=False
        ),
        ANDROID_RES_DIR / "mipmap" / "ic_launcher.xml": android_vector(
            strokes, MARGIN, background=True
        ),
        ANDROID_RES_DIR / "mipmap-anydpi-v26" / "ic_launcher.xml": ADAPTIVE_ICON,
        ANDROID_RES_DIR / "values" / "ic_launcher_colors.xml": ICON_COLORS,
    }
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"{path.relative_to(REPO_ROOT)}: {len(content)} bytes")


if __name__ == "__main__":
    main()
