"""Training data for the encoder: image pools per character and the batch sampler.

Pools (all uint8, 64×64, ink = 255):

* synthetic drawings, pre-generated by the ``encoderdata`` stage;
* glyph renders, downsampled from the 128 px renders of the ``glyphs`` stage;
* optionally, real training drawings (train-split writers, non-zero-shot characters).

Each pool is sorted by character so that ``offsets[k]:offsets[k + 1]`` are the rows of the
k-th character.

A batch holds distinct characters. Part of it is random, the rest is built from
neighbourhoods: a seed character plus some of its nearest look-alikes from *other*
confusable groups, which gives the loss hard negatives. The neighbours start from HOG
similarity of the glyph renders and are refreshed during training from the model's own
glyph embeddings.
"""

from dataclasses import dataclass

import numpy as np
import torch

from glyphsketch.baselines import hog_features


@dataclass
class CharacterPool:
    """Images of many characters, grouped: rows ``offsets[k]:offsets[k + 1]`` are character k."""

    images: np.ndarray
    offsets: np.ndarray

    def count(self, character: int) -> int:
        return int(self.offsets[character + 1] - self.offsets[character])

    def pick(self, characters: np.ndarray, rng: np.random.Generator) -> np.ndarray:
        """One random row index for each character (each must have at least one image)."""
        starts = self.offsets[characters]
        counts = self.offsets[characters + 1] - starts
        return starts + (rng.random(len(characters)) * counts).astype(np.int64)


def group_by_character(
    images: np.ndarray, code_points: np.ndarray, characters: np.ndarray
) -> CharacterPool:
    """Sort images by character (in the order of ``characters``) and build the offsets.

    Images of code points that are not in ``characters`` are dropped.
    """
    position = {int(code_point): index for index, code_point in enumerate(characters.tolist())}
    keys = np.array([position.get(int(cp), -1) for cp in code_points.tolist()], dtype=np.int64)
    keep = np.flatnonzero(keys >= 0)
    order = keep[np.argsort(keys[keep], kind="stable")]
    counts = np.bincount(keys[keep], minlength=len(characters))
    offsets = np.concatenate([[0], np.cumsum(counts)]).astype(np.int64)
    return CharacterPool(images=images[order], offsets=offsets)


@dataclass
class TrainingData:
    characters: np.ndarray
    """Code points, index k is character k."""
    groups: np.ndarray
    """Confusable-group id of each character (its own index when it is in no group)."""
    synthetic: CharacterPool
    glyphs: CharacterPool
    real: CharacterPool | None = None


def group_ids(characters: np.ndarray, group_of: dict[int, int]) -> np.ndarray:
    representative = [group_of.get(int(cp), int(cp)) for cp in characters.tolist()]
    _, ids = np.unique(np.array(representative), return_inverse=True)
    return ids.astype(np.int64)


def same_group_mask(groups: np.ndarray) -> torch.Tensor:
    """(B, B) True where two different batch entries share a confusable group."""
    tensor = torch.from_numpy(groups)
    mask = tensor[:, None] == tensor[None, :]
    mask.fill_diagonal_(False)
    return mask


def nearest_other_group(
    features: np.ndarray, groups: np.ndarray, neighbours: int, chunk: int = 1024
) -> np.ndarray:
    """For each character, the ``neighbours`` most similar characters of another group.

    ``features`` are unit vectors (one per character); similarity is the dot product.
    """
    result = np.empty((len(features), neighbours), dtype=np.int64)
    for start in range(0, len(features), chunk):
        block = features[start : start + chunk] @ features.T
        rows = np.arange(start, min(start + chunk, len(features)))
        block[groups[rows][:, None] == groups[None, :]] = -np.inf
        top = np.argpartition(-block, neighbours, axis=1)[:, :neighbours]
        top_scores = np.take_along_axis(block, top, axis=1)
        result[rows] = np.take_along_axis(top, np.argsort(-top_scores, axis=1), axis=1)
    return result


def glyph_hog_neighbours(data: TrainingData, neighbours: int) -> np.ndarray:
    """Initial hard-negative candidates: mean HOG descriptor of each character's renders."""
    images = data.glyphs.images.astype(np.float32) / 255.0
    descriptors = hog_features(images)
    sums = np.add.reduceat(descriptors, data.glyphs.offsets[:-1], axis=0)
    norms = np.linalg.norm(sums, axis=1, keepdims=True)
    return nearest_other_group(sums / np.maximum(norms, 1e-8), data.groups, neighbours)


class BatchSampler:
    """Batches of distinct characters, part random and part hard-negative neighbourhoods."""

    def __init__(
        self,
        character_count: int,
        batch_size: int,
        neighbours: np.ndarray,
        hard_fraction: float,
        neighbourhood_size: int,
        rng: np.random.Generator,
    ) -> None:
        if batch_size > character_count:
            raise ValueError("A batch cannot hold more characters than there are")
        self.character_count = character_count
        self.batch_size = batch_size
        self.neighbours = neighbours
        self.hard_fraction = hard_fraction
        self.neighbourhood_size = neighbourhood_size
        self.rng = rng

    def update_neighbours(self, neighbours: np.ndarray) -> None:
        self.neighbours = neighbours

    def sample(self) -> np.ndarray:
        chosen: list[int] = []
        taken = np.zeros(self.character_count, dtype=bool)
        hard_target = int(self.batch_size * self.hard_fraction)
        while len(chosen) < hard_target:
            seed = int(self.rng.integers(self.character_count))
            if taken[seed]:
                continue
            candidates = self.neighbours[seed]
            picks = self.rng.permutation(candidates)[: self.neighbourhood_size - 1]
            for character in (seed, *picks.tolist()):
                if not taken[character] and len(chosen) < hard_target:
                    taken[character] = True
                    chosen.append(int(character))
        remaining = np.flatnonzero(~taken)
        fill = self.rng.choice(remaining, size=self.batch_size - len(chosen), replace=False)
        return np.concatenate([np.array(chosen, dtype=np.int64), fill.astype(np.int64)])


def to_tensor(images: np.ndarray) -> torch.Tensor:
    """uint8 (N, S, S) images to float (N, 1, S, S) with ink = 1."""
    return torch.from_numpy(images).unsqueeze(1).float().div_(255.0)


@dataclass(frozen=True)
class Batch:
    first_view: torch.Tensor
    second_view: torch.Tensor
    glyphs: torch.Tensor
    same_group: torch.Tensor
    characters: np.ndarray


def assemble_batch(
    data: TrainingData, characters: np.ndarray, real_probability: float, rng: np.random.Generator
) -> Batch:
    """Two drawing views and one glyph render per character.

    With probability ``real_probability`` a view is a real drawing, for characters that
    have real training drawings.
    """
    first = data.synthetic.images[data.synthetic.pick(characters, rng)]
    second = data.synthetic.images[data.synthetic.pick(characters, rng)]
    if data.real is not None and real_probability > 0:
        has_real = (data.real.offsets[characters + 1] - data.real.offsets[characters]) > 0
        for view in (first, second):
            use_real = has_real & (rng.random(len(characters)) < real_probability)
            if use_real.any():
                view[use_real] = data.real.images[data.real.pick(characters[use_real], rng)]
    glyphs = data.glyphs.images[data.glyphs.pick(characters, rng)]
    return Batch(
        first_view=to_tensor(first),
        second_view=to_tensor(second),
        glyphs=to_tensor(glyphs),
        same_group=same_group_mask(data.groups[characters]),
        characters=characters,
    )
