"""Assemble the real-data sample set from Detexify, Omniglot and UJI Pen Characters.

Only samples whose label maps to a character that has at least one glyph render are kept,
since the recognizer can return nothing else. The ``realdata`` stage writes the samples
to ``samples.npz`` and a Markdown summary.
"""

from collections import Counter, defaultdict
from collections.abc import Iterator
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from glyphsketch.charset import CharacterRecord
from glyphsketch.realdata import detexify, omniglot, uji
from glyphsketch.realdata.samples import DrawingSample, SampleSet
from glyphsketch.realdata.splits import (
    TEST_FRACTION,
    ZERO_SHOT_FRACTION,
    held_out_mask,
    zero_shot_mask,
)

SAMPLES_FILE = "samples.npz"
REPORT_FILE = "real_data_report.md"


@dataclass
class DetexifyLabelCounts:
    kept: Counter[str] = field(default_factory=Counter)
    outside_glyph_set: Counter[str] = field(default_factory=Counter)
    no_code_point: Counter[str] = field(default_factory=Counter)


def _detexify_samples(
    dump_path: Path, allowed: set[int], counts: DetexifyLabelCounts
) -> Iterator[DrawingSample]:
    mapping = detexify.load_mapping()
    for record in detexify.parse_dump(dump_path):
        entry = mapping.get(record.key)
        if entry is None or entry.code_point is None:
            counts.no_code_point[record.key] += 1
            continue
        if entry.code_point not in allowed:
            counts.outside_glyph_set[record.key] += 1
            continue
        if not record.strokes:
            continue
        counts.kept[record.key] += 1
        yield DrawingSample(
            dataset=detexify.DATASET_NAME,
            sample_id=str(record.sample_id),
            writer=detexify.pseudo_writer(record.first_timestamp_ms),
            label=record.key,
            code_point=entry.code_point,
            strokes=record.strokes,
        )


def build_real_samples(
    allowed_code_points: set[int], detexify_dir: Path, omniglot_dir: Path, uji_dir: Path
) -> tuple[SampleSet, DetexifyLabelCounts]:
    counts = DetexifyLabelCounts()

    def all_samples() -> Iterator[DrawingSample]:
        yield from _detexify_samples(detexify_dir / detexify.DUMP_FILE, allowed_code_points, counts)
        yield from omniglot.omniglot_samples(
            omniglot_dir, omniglot.load_mapping(), allowed_code_points
        )
        yield from uji.uji_samples(uji_dir, allowed_code_points)

    return SampleSet.from_samples(all_samples()), counts


def real_data_report(
    samples: SampleSet, counts: DetexifyLabelCounts, characters: dict[int, CharacterRecord]
) -> str:
    is_test = held_out_mask(samples)
    is_zero_shot = zero_shot_mask(samples)
    lines = [
        "# Real handwriting data",
        "",
        "Generated by the `realdata` pipeline stage. Test writers are chosen by hashing the",
        f"writer id ({TEST_FRACTION:.0%} of writers); zero-shot characters by hashing the code",
        f"point ({ZERO_SHOT_FRACTION:.0%} of characters with real data). Training never sees",
        "test writers or real drawings of zero-shot characters.",
        "",
        "| Dataset | Samples | Characters | Writers | Test samples | Test writers |",
        "|---------|--------:|-----------:|--------:|-------------:|-------------:|",
    ]
    for dataset in sorted(set(samples.datasets.tolist())):
        mask = samples.datasets == dataset
        writers = set(samples.writers[mask].tolist())
        test_writers = set(samples.writers[mask & is_test].tolist())
        lines.append(
            f"| {dataset} | {int(mask.sum())} | {len(set(samples.code_points[mask].tolist()))} | "
            f"{len(writers)} | {int((mask & is_test).sum())} | {len(test_writers)} |"
        )
    all_characters = set(samples.code_points.tolist())
    zero_shot_characters = set(samples.code_points[is_zero_shot].tolist())
    lines += [
        f"| **all** | {len(samples)} | {len(all_characters)} | "
        f"{len(set(zip(samples.datasets.tolist(), samples.writers.tolist(), strict=True)))} | "
        f"{int(is_test.sum())} | – |",
        "",
        f"Zero-shot characters: {len(zero_shot_characters)} of {len(all_characters)} "
        f"({int((is_test & is_zero_shot).sum())} test samples).",
        "",
        "Detexify labels (keys) by mapping status:",
        "",
        f"- kept: {len(counts.kept)} keys, {sum(counts.kept.values())} samples",
        f"- mapped to a character outside the glyph set: {len(counts.outside_glyph_set)} keys, "
        f"{sum(counts.outside_glyph_set.values())} samples",
        f"- no single-code-point equivalent: {len(counts.no_code_point)} keys, "
        f"{sum(counts.no_code_point.values())} samples",
        "",
        "## Samples by Unicode block",
        "",
        "| Block | Samples | Characters | Test samples |",
        "|-------|--------:|-----------:|-------------:|",
    ]
    by_block: dict[str, list[int]] = defaultdict(list)
    for index, code_point in enumerate(samples.code_points.tolist()):
        record = characters.get(code_point)
        by_block[record.block if record else "?"].append(index)
    for block, rows in sorted(by_block.items(), key=lambda item: -len(item[1])):
        rows_array = np.array(rows)
        lines.append(
            f"| {block} | {len(rows)} | {len(set(samples.code_points[rows_array].tolist()))} | "
            f"{int(is_test[rows_array].sum())} |"
        )
    return "\n".join(lines) + "\n"
