"""Detexify's training data (http://detexify.kirelabs.org), licensed under the ODbL 1.0.

The dump is a PostgreSQL table ``samples(id, key, strokes)``. ``key`` names a LaTeX symbol
(``<package>-<encoding>-_<command>``) and ``strokes`` is JSON ``[[[x, y, t], ...], ...]``
in canvas pixels (y down) with millisecond timestamps.

The data has no writer ids. The UTC day of a sample's first timestamp serves as a
pseudo-writer, so the train/test split keeps each day (and therefore almost every drawing
session) on one side. See DECISIONS.md.

``resources/detexify_unicode.tsv`` maps each key to a code point. It was generated by
``glyphsketch.tools.detexify_mapping`` from W3C's unicode.xml plus hand-checked entries.
"""

import gzip
import json
from collections.abc import Iterator
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import numpy as np

from glyphsketch.charset import parse_code_point
from glyphsketch.download import download_file
from glyphsketch.paths import RESOURCES_DIR
from glyphsketch.realdata.samples import DrawingSample

DATASET_NAME = "detexify"
MAPPING_PATH = RESOURCES_DIR / "detexify_unicode.tsv"
DUMP_FILE = "detexify.sql.gz"
SYMBOLS_FILE = "symbols.json"


@dataclass(frozen=True)
class DriveFile:
    name: str
    drive_id: str
    resource_key: str
    sha256: str

    @property
    def url(self) -> str:
        return (
            "https://drive.usercontent.google.com/download?"
            f"id={self.drive_id}&resourcekey={self.resource_key}&export=download&confirm=t"
        )


# The files in the Google Drive folder linked from https://github.com/kirel/detexify-data.
DETEXIFY_FILES = (
    DriveFile(
        DUMP_FILE,
        "0ByuYordD0JBRV01NM2pmNlpfNUE",
        "0-CZHt-PBM7v0hty25FF5wsg",
        "a270abcd031582364f6ede1a5dac3f3c3a6cd2d15c2b61f7bb2726b0f716d128",
    ),
    DriveFile(
        SYMBOLS_FILE,
        "0ByuYordD0JBRU1Y3Q3VSNk9kdE0",
        "0-V2m8tmPfD8eyNe4GGrhSxw",
        "13bfd78164d92f4fb73856926fcd2c272ec171b5c35110de76c4ec6c0cdfced0",
    ),
    DriveFile(
        "README.txt",
        "0ByuYordD0JBRb3hFUUlSRkEyNmM",
        "0-HEZkhosOQw_GQWHkHILphA",
        "55f108116939166b85a8b30113917a01d8675eb1ad1c7c81cba170e983918b99",
    ),
)
LICENSE_URL = (
    "https://raw.githubusercontent.com/kirel/detexify-data/"
    "daf0cab646a7b5c3d16508a1982e3c397d13580a/odbl-10.txt"
)
LICENSE_SHA256 = "a221a27af5e4ef5a9cecce097c718c28f1aaf7d368cb57c994aa447c68d9defc"


def download_detexify(destination_dir: Path) -> None:
    for drive_file in DETEXIFY_FILES:
        download_file(drive_file.url, destination_dir / drive_file.name, drive_file.sha256)
    download_file(LICENSE_URL, destination_dir / "odbl-10.txt", LICENSE_SHA256)


@dataclass(frozen=True)
class DetexifyRecord:
    sample_id: int
    key: str
    strokes: list[np.ndarray]
    first_timestamp_ms: int | None


def parse_dump(path: Path) -> Iterator[DetexifyRecord]:
    """Yield every sample of the ``COPY samples (id, key, strokes)`` block of the dump."""
    opener = gzip.open if path.name.endswith(".gz") else open
    with opener(path, "rt", encoding="utf-8") as stream:
        in_copy_block = False
        for line in stream:
            if not in_copy_block:
                in_copy_block = line.startswith("COPY samples (id, key, strokes)")
                continue
            if line.startswith("\\."):
                return
            sample_id, key, strokes_json = line.rstrip("\n").split("\t")
            raw_strokes = json.loads(strokes_json)
            strokes = [
                np.array([[point[0], point[1]] for point in stroke], dtype=np.float32)
                for stroke in raw_strokes
                if stroke
            ]
            first_timestamp = None
            if raw_strokes and raw_strokes[0] and len(raw_strokes[0][0]) > 2:
                first_timestamp = int(raw_strokes[0][0][2])
            yield DetexifyRecord(int(sample_id), key, strokes, first_timestamp)


def pseudo_writer(first_timestamp_ms: int | None) -> str:
    if first_timestamp_ms is None:
        return "day-unknown"
    day = datetime.fromtimestamp(first_timestamp_ms / 1000, UTC).date()
    return f"day-{day.isoformat()}"


@dataclass(frozen=True)
class MappingEntry:
    key: str
    command: str
    code_point: int | None
    source: str
    note: str


def load_mapping(path: Path = MAPPING_PATH) -> dict[str, MappingEntry]:
    entries: dict[str, MappingEntry] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        key, command, code_point, source, note = (line.split("\t") + [""] * 5)[:5]
        entries[key] = MappingEntry(
            key=key,
            command=command,
            code_point=parse_code_point(code_point) if code_point else None,
            source=source,
            note=note,
        )
    return entries


def detexify_samples(
    dump_path: Path, mapping: dict[str, MappingEntry], allowed_code_points: set[int]
) -> Iterator[DrawingSample]:
    """Samples whose key maps to a code point in ``allowed_code_points``."""
    for record in parse_dump(dump_path):
        entry = mapping.get(record.key)
        if entry is None or entry.code_point not in allowed_code_points or not record.strokes:
            continue
        yield DrawingSample(
            dataset=DATASET_NAME,
            sample_id=str(record.sample_id),
            writer=pseudo_writer(record.first_timestamp_ms),
            label=record.key,
            code_point=entry.code_point,
            strokes=record.strokes,
        )
